"""Emit lightweight OSCAL-inspired JSON from mapped policy statements."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Iterable

from grc_pdf_mapper.models import MappedStatement


def to_component_definition(
    *,
    component_title: str,
    mapped: Iterable[MappedStatement],
    doc_id: str,
) -> dict:
    """
    Build a minimal OSCAL component-definition shaped document.

    This is intentionally pragmatic: enough for import experiments and
    FedRAMP-adjacent tooling, not a full NIST validator pass.
    """
    mapped_list = list(mapped)
    now = datetime.now(timezone.utc).isoformat()
    control_impls: list[dict] = []
    seen: set[str] = set()

    for row in mapped_list:
        for hit in row.mappings:
            if hit.framework != "NIST 800-53":
                continue
            key = hit.control_id.upper()
            if key in seen:
                continue
            seen.add(key)
            control_impls.append(
                {
                    "uuid": str(uuid.uuid4()),
                    "control-id": hit.control_id.lower(),
                    "description": row.statement.text,
                    "props": [
                        {"name": "policy-statement-id", "value": row.statement.statement_id},
                        {"name": "obligation-strength", "value": row.statement.strength.value},
                        {"name": "mapping-source", "value": hit.source},
                    ],
                }
            )

    return {
        "component-definition": {
            "uuid": str(uuid.uuid4()),
            "metadata": {
                "title": component_title,
                "last-modified": now,
                "version": "0.1.0",
                "oscal-version": "1.1.2",
                "remarks": f"Generated by grc-pdf-mapper from document {doc_id}",
            },
            "components": [
                {
                    "uuid": str(uuid.uuid4()),
                    "type": "policy",
                    "title": component_title,
                    "description": f"Corporate policy/procedure extracted from {doc_id}",
                    "control-implementations": [
                        {
                            "uuid": str(uuid.uuid4()),
                            "source": (
                                "https://raw.githubusercontent.com/usnistgov/oscal-content/"
                                "main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json"
                            ),
                            "description": "Implemented controls inferred from policy obligations",
                            "implemented-requirements": control_impls,
                        }
                    ],
                }
            ],
        }
    }


def to_assessment_results(
    *,
    title: str,
    mapped: Iterable[MappedStatement],
) -> dict:
    """Sketch assessment-results entries for each MUST/SHALL obligation."""
    results = []
    for row in mapped:
        if row.statement.strength.value not in {"must", "shall", "prohibited"}:
            continue
        results.append(
            {
                "uuid": str(uuid.uuid4()),
                "title": row.statement.heading_path[-1] if row.statement.heading_path else "Obligation",
                "description": row.statement.text,
                "props": [
                    {"name": "statement-id", "value": row.statement.statement_id},
                    {
                        "name": "mapped-controls",
                        "value": ", ".join(f"{h.framework}:{h.control_id}" for h in row.mappings[:8]),
                    },
                ],
                "status": {"state": "satisfied_as_documented"},
            }
        )
    return {
        "assessment-results": {
            "uuid": str(uuid.uuid4()),
            "metadata": {
                "title": title,
                "last-modified": datetime.now(timezone.utc).isoformat(),
                "version": "0.1.0",
                "oscal-version": "1.1.2",
            },
            "results": results,
        }
    }
